### ISSUE TITLE
Could anyone please help to resolve this error

### ISSUE THREAD

**Issue by tejukasula** [2gunsu/SPL2021-FEN#2]
usage: ipykernel_launcher.py [-h] --data_root DATA_ROOT
                             [--noise_type {none,gaussian,snp}]
                             [--noise_params NOISE_PARAMS [NOISE_PARAMS ...]]
                             --output_dir OUTPUT_DIR [--epochs EPOCHS]
                             [--batch BATCH] [--num_workers NUM_WORKERS]
                             [--num_classes NUM_CLASSES]
                             [--arch {R50-FPN,R101-FPN,X101-FPN}]
                             [--input_size INPUT_SIZE]
                             [--fen_levels {p2,p3,p4,p5,p6} [{p2,p3,p4,p5,p6} ...]]
ipykernel_launcher.py: error: the following arguments are required: --data_root, --output_dir
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

**Comment by 2gunsu** [comment]
Hello. 
From the error you mentioned, it looks like you are trying to run the code with jupyter notebook, is that right?

**Comment by tejukasula** [comment]
No sir,
I'm trying to run the code from Google colab.can you please help me solve
the error.

**Comment by 2gunsu** [comment]
Our code uses **argparse** to pass arguments to the program.  
But this is not directly available in Jupyter Notebook or Google Colab. That's why the error you commented is occured.

I recommend running with ```run_train_net.py``` instead of ```run_train.py```.   
Before execution, please modify variables shown below ​​in ```run_train_net.py```.

```python
    backbone_arch: str = 'X101-FPN'
    data_root: str = ""
    output_dir: str = ""

    input_size: Union[Tuple[int, int], int] = 800
    noise_type: str = ''
    noise_params: Any = []

    num_epoch = 10
    num_class = 1
    num_workers = 8
    batch_size = 4
    base_lr = 2.0E-03

    log_period: int = 1
    val_period: int = 5
    checkpoint_period: int = 100

    use_fen: bool = False
    levels: List[str] = []
    patch_per_img: int = 4
    patch_size: int = 32
    min_patch_size: int = 20
    erase_ratio: float = 0.5
    soften_ratio: float = 0.6
```

**Comment by tejukasula** [comment]
I'm getting this error If I try to run "run_train_net.py",on google colab.

Please help me to solve this error.



Config and Weights for "X101-FPN" is loaded.

---------------------------------------------------------------------------

AssertionError                            Traceback (most recent call last)

<ipython-input-16-a84478dd1db0> <https://localhost:8080/#> in <module>
    90         cfg, num_epoch, num_class, base_lr, num_workers,
batch_size,     91         data_root, input_size, noise_type,
noise_params, log_period,
---> 92         checkpoint_period, val_period, output_dir     93     )
    94     cfg = add_fen_params(cfg, levels, patch_per_img,
patch_size, min_patch_size, erase_ratio, soften_ratio)


------------------------------
1 frames
------------------------------

/content/utils/config.py <https://localhost:8080/#> in
register_datasets(data_root)    127     128 def
register_datasets(data_root: str):
--> 129     assert os.path.isdir(data_root), "Cannot find 'data_root'
you entered."    130     131     # Register Train Data


AssertionError: Cannot find 'data_root' you entered.

**Comment by 2gunsu** [comment]
Oh, Sorry. I think I misunderstood. I'm out of schedule right now and I'll get back to you in a few hours.

**Comment by tejukasula** [comment]
Okay sir,Thank you.
Please help me when you are available.

**Comment by tejukasula** [comment]
Could you please say where it is preferred to run the code other than
google colab.

**Comment by 2gunsu** [comment]
I'm really sorry for the late reply.  

```
/content/utils/config.py <https://localhost:8080/#> in
register_datasets(data_root)    127     128 def
register_datasets(data_root: str):
--> 129     assert os.path.isdir(data_root), "Cannot find 'data_root'
you entered."    130     131     # Register Train Data

AssertionError: Cannot find 'data_root' you entered.
```
Judging from this error, it seems that you did not set the value of ```data_root``` in ```run_train_net.py``` or set it incorrectly. You can save the dataset in google drive, link google colab with google drive, and set the value of ```data_root``` to the path stored in google drive.

To use the google drive file in google colab, add the code below to the top.
```python
from google.colab import drive
drive.mount('/content/gdrive')
```

Or, you may want to refer to the post below.
https://stackoverflow.com/questions/48376580/google-colab-how-to-read-data-from-my-google-drive

If you have a Linux server with a GPU, it is common to run it using PuTTY or Vscode.  
However, if you do not have a Linux server or only use a Windows environment, google colab seems to be the best option.

**Comment by tejukasula** [comment]
I have linked the google drive to google colab, then I'm getting this
error.Is there a way to solve this error.

Config and Weights for "X101-FPN" is loaded.

WARNING:detectron2.data.datasets.coco:
Category ids in annotations are not in [1, #categories]! We'll apply a
mapping for you.


---------------------------------------------------------------------------

AssertionError                            Traceback (most recent call last)

<ipython-input-17-91888471c7fb> <https://localhost:8080/#> in <module>
    96      97     # Start Training
---> 98     trainer = FENTrainer(cfg=cfg)     99
trainer.resume_or_load(False)    100     trainer.train()


------------------------------
3 frames
------------------------------

/content/data/mapper.py <https://localhost:8080/#> in
get_noiser(noise_type, noise_params)     41      42     assert
noise_type in MAP_DICT.keys(), \
---> 43         f"Argument 'noise_type' must be one in
{list(MAP_DICT.keys())}."     44     return MAP_DICT.get(noise_type,
'none')(noise_params)     45

AssertionError: Argument 'noise_type' must be one in ['none',
'gaussian', 'snp'].

**Comment by 2gunsu** [comment]
The error message is  

```
/content/data/mapper.py <https://localhost:8080/#> in
get_noiser(noise_type, noise_params)     41      42     assert
noise_type in MAP_DICT.keys(), \
---> 43         f"Argument 'noise_type' must be one in
{list(MAP_DICT.keys())}."     44     return MAP_DICT.get(noise_type,
'none')(noise_params)     45

AssertionError: Argument 'noise_type' must be one in ['none',
'gaussian', 'snp'].
```

This is a problem caused by not entering the ```noise_type``` variable in ```run_train_net.py```. Please fill in all variables appropriately as described below.

```
if __name__ == '__main__':


    # Parameters


    #
    # 'backbone_arch':
    #           Select one in ['R50-FPN', 'R101-FPN', 'X101-FPN'].
    #
    # 'data_root':
    #           See the 'Datasets and Preparation' section in the following link for the data structure.
    #           https://github.com/2gunsu/SPL2021-FEN
    #
    # 'output_dir':
    #           Output directory where training results are saved to.
    #
    # 'input_size':
    #           Determine the size of the image to be used for training.
    #
    # 'noise_type':
    #           Decide what kind of noise to add to the data batch.
    #           Select one in ['none', 'gaussian', 'snp'].
    #           ('snp' represents 'Salt & Pepper')
    #
    # 'noise_params':
    #           This parameter controls noise, and the input type is different depending on the type of noise.
    #             - When 'noise_type' is 'none',
    #                 This argument will be ignored.
    #
    #             - When 'noise_type' is 'gaussian',
    #                 Please enter the standard deviation of Gaussian noise.
    #                 The input type must be Union[int, List[int]].
    #                   [EX] 50, [50], [25, 50] are all possible.
    #
    #             - When 'noise_type' is 'snp',
    #                 Please enter the amount of salt & pepper noise.
    #                 The input type must be float which range in (0.0, 1.0).
    #                 It is recommended to use a value of 0.15 or less.
    #


    backbone_arch: str = 'X101-FPN'
    data_root: str = ""
    output_dir: str = ""


    input_size: Union[Tuple[int, int], int] = 800
    noise_type: str = ''
    noise_params: Any = []


    num_epoch = 10
    num_class = 1
    num_workers = 8
    batch_size = 4
    base_lr = 2.0E-03


    log_period: int = 1
    val_period: int = 5
    checkpoint_period: int = 100


    #
    # 'levels':
    #           The levels of the feature map to be enhanced.
    #           Available feature levels are ['p2', 'p3', 'p4', 'p5', 'p6'].
    #           Several combinations can be made using these elements.
    #               [EX] ['p2', 'p5'] or ['p4', 'p5'] or ['p5']
    #           Please note that using up all levels will require large V-RAM.
    #


    use_fen: bool = False
    levels: List[str] = []
    patch_per_img: int = 4
    patch_size: int = 32
    min_patch_size: int = 20
    erase_ratio: float = 0.5
    soften_ratio: float = 0.6
```

**Comment by tejukasula** [comment]
I have entered the same as you mentioned,still getting the same error.


if __name__ == '__main__':

    # Parameters

    #
    # 'backbone_arch':
    #           Select one in ['R50-FPN', 'R101-FPN', 'X101-FPN'].
    #
    # 'data_root':

#           See the 'Datasets and Preparation' section in the
following link for the data structure.
    #           https://github.com/2gunsu/SPL2021-FEN
    #
    # 'output_dir':
    #           Output directory where training results are saved to.
    #
    # 'input_size':
    #           Determine the size of the image to be used for training.
    #
    # 'noise_type':
    #           Decide what kind of noise to add to the data batch.
    #           Select one in ['none', 'gaussian', 'snp'].
    #           ('snp' represents 'Salt & Pepper')
    #
    # 'noise_params':

#           This parameter controls noise, and the input type is
different depending on the type of noise.
    #             - When 'noise_type' is 'none',
    #                 This argument will be ignored.
    #
    #             - When 'noise_type' is 'gaussian',
    #                 Please enter the standard deviation of Gaussian noise.
    #                 The input type must be Union[int, List[int]].
    #                   [EX] 50, [50], [25, 50] are all possible.
    #
    #             - When 'noise_type' is 'snp',
    #                 Please enter the amount of salt & pepper noise.

#                 The input type must be float which range in (0.0, 1.0).
    #                 It is recommended to use a value of 0.15 or less.
    #

    backbone_arch: str = 'X101-FPN'
    data_root: str = "/content/gdrive/MyDrive/DOTA"
    output_dir: str = ""

    input_size: Union[Tuple[int, int], int] = 800
    noise_type: str = ''
    noise_params: Any = []

    num_epoch = 10
    num_class = 1
    num_workers = 8
    batch_size = 4
    base_lr = 2.0E-03

    log_period: int = 1
    val_period: int = 5
    checkpoint_period: int = 100

    #
    # 'levels':
    #           The levels of the feature map to be enhanced.
    #           Available feature levels are ['p2', 'p3', 'p4', 'p5', 'p6'].
    #           Several combinations can be made using these elements.
    #               [EX] ['p2', 'p5'] or ['p4', 'p5'] or ['p5']

#           Please note that using up all levels will require large V-RAM.
    #

    use_fen: bool = False
    levels: List[str] = []
    patch_per_img: int = 4
    patch_size: int = 32
    min_patch_size: int = 20
    erase_ratio: float = 0.5
    soften_ratio: float = 0.6

**Comment by 2gunsu** [comment]
No.  
It doesn't mean to use the code I attached as it is, it means to fill in the empty variables such as ```output_dir```, ```noise_type```, ```noise_params```, and ```levels``` by referring to the comments in the code.

**Comment by tejukasula** [comment]
I have all the empty variables by referring the comments in the code,still
getting this error.

Config and Weights for "X101-FPN" is loaded.

---------------------------------------------------------------------------

AssertionError                            Traceback (most recent call last)

<ipython-input-18-66335798ea41> <https://localhost:8080/#> in <module>
    90         cfg, num_epoch, num_class, base_lr, num_workers,
batch_size,     91         data_root, input_size, noise_type,
noise_params, log_period,
---> 92         checkpoint_period, val_period, output_dir     93     )
    94     cfg = add_fen_params(cfg, levels, patch_per_img,
patch_size, min_patch_size, erase_ratio, soften_ratio)


------------------------------
3 frames
------------------------------

/usr/local/lib/python3.7/dist-packages/detectron2/data/catalog.py
<https://localhost:8080/#> in register(self, name, func)     35
 """     36         assert callable(func), "You must register a
function with `DatasetCatalog.register`!"
---> 37         assert name not in self, "Dataset '{}' is already
registered!".format(name)     38         self[name] = func     39

AssertionError: Dataset 'train' is already registered!

**Comment by 2gunsu** [comment]
Ummm... that's weird 🤔.  
Could you please write the entire ```run_train_net.py``` you used and the error message here?

**Comment by tejukasula** [comment]
Can you please say how much GB is required to run and how much time it
usually takes to complete.Google colab is saying  "You cannot currently
connect to a GPU due to usage limits in Colab." Is there any way to
resolve this issue?

**Comment by 2gunsu** [comment]
I did this experiment early last year, so I can't remember the running time or GPU memory consumption exactly.  At the time, I was using an RTX Titan (24 GB), and I think I probably needed this level of memory.  

As far as I know, the free tier of google colab only allows you to use GPU memory up to 12GB, but if you need higher memory than this, there seems to be only a way to use it by subscribing to [Colab Pro or Pro+](https://colab.research.google.com/signup) or purchasing a GPU of 24GB or more.

**Comment by tejukasula** [comment]
Sir,can you please suggest any other platform other than colab.

**Comment by 2gunsu** [comment]
I haven't been in this field for a long time 🤔, but as far as I know, Google Colab is the only platform where you can get a reasonably priced (or free) GPU. It is also possible to rent a GPU server from [Amazon Cloud](https://aws.amazon.com), but I know that it is very expensive.

**Comment by 2gunsu** [comment]
Due to inactivity, I close this issue.
If you have any other questions, feel free to leave a comment here.
Thank You. 😊

**Comment by tejukasula** [comment]
Could you please say how the output is stored either in form of images or
binary format? Please do clarify.

**Comment by 2gunsu** [comment]
I think I can help you if you tell me in detail what the **'output'** you mentioned is.  
Just using the word **'output'** is too vague.

**Comment by tejukasula** [comment]
Output in the sense will the output be displayed as images or in the form
of binary format or json file types.
If the output is in json format or binary form.How to convert that large
file to images.
Please clarify this sir.

**Comment by 2gunsu** [comment]
Oh, I understand what you said.  
I think you asked how to visualize it, but come to think of it, I didn't put that part in this code.  

I'll take a look and let you know. (However, it has been over a year since I have not seen this code, and I am very busy at the moment, so please understand that it may take a while.)

**Comment by tejukasula** [comment]
Sir,if we reduce the number of epochs and batch size can we minimize the
memory consumption of gpu to 15gb and in what format is the output saved in
output directory?please clarify this.

**Comment by tejukasula** [comment]
Sir,if we reduce the number of epochs and batch size can we minimize the
memory consumption of gpu to 15gb and in what format is the output saved in
output directory?

please clarify this.

**Comment by tejukasula** [comment]
This is the entire code of run_train_net.py

import os
import warnings
from detectron2.config import get_cfg
from typing import Any, List, Union, Tuple

from module import RCNN
from engine.trainer import FENTrainer
from utils.config import
 save_config, load_cfg_arch, set_cfg_params, add_fen_params
warnings.filterwarnings('ignore')


if __name__ == '__main__':

    # Parameters

    #
    # 'backbone_arch':
    #           Select one in ['R50-FPN', 'R101-FPN', 'X101-FPN'].
    #
    # 'data_root':

#           See the 'Datasets and Preparation' section in the
following link for the data structure.
    #           https://github.com/2gunsu/SPL2021-FEN
    #
    # 'output_dir':
    #           Output directory where training results are saved to.
    #
    # 'input_size':
    #           Determine the size of the image to be used for training.
    #
    # 'noise_type':
    #           Decide what kind of noise to add to the data batch.
    #           Select one in ['none', 'gaussian', 'snp'].
    #           ('snp' represents 'Salt & Pepper')
    #
    # 'noise_params':

#           This parameter controls noise, and the input type is
different depending on the type of noise.
    #             - When 'noise_type' is 'none',
    #                 This argument will be ignored.
    #
    #             - When 'noise_type' is 'gaussian',
    #                 Please enter the standard deviation of Gaussian noise.
    #                 The input type must be Union[int, List[int]].
    #                   [EX] 50, [50], [25, 50] are all possible.
    #
    #             - When 'noise_type' is 'snp',
    #                 Please enter the amount of salt & pepper noise.

#                 The input type must be float which range in (0.0, 1.0).
    #                 It is recommended to use a value of 0.15 or less.
    #

    backbone_arch: str = 'X101-FPN'
    data_root: str = "/content/gdrive/MyDrive/DOTA"
    output_dir: str = "/content/gdrive/MyDrive/output directory"

    input_size: Union[Tuple[int, int], int] = 800
    noise_type: str = 'snp'
    noise_params: Any = [0.15]

    num_epoch = 10
    num_class = 1
    num_workers = 8
    batch_size = 4
    base_lr = 2.0E-03

    log_period: int = 1
    val_period: int = 5
    checkpoint_period: int = 100

    #
    # 'levels':
    #           The levels of the feature map to be enhanced.
    #           Available feature levels are ['p2', 'p3', 'p4', 'p5', 'p6'].
    #           Several combinations can be made using these elements.
    #               [EX] ['p2', 'p5'] or ['p4', 'p5'] or ['p5']

#           Please note that using up all levels will require large V-RAM.
    #

    use_fen: bool = False
    levels: List[str] =['p5']
    patch_per_img: int = 4
    patch_size: int = 32
    min_patch_size: int = 20
    erase_ratio: float = 0.5
    soften_ratio: float = 0.6

    # Set Configuration
    cfg = get_cfg()
    cfg = load_cfg_arch(cfg, arch_name=backbone_arch)
    cfg = set_cfg_params(
        cfg, num_epoch, num_class, base_lr, num_workers, batch_size,
        data_root, input_size, noise_type, noise_params, log_period,
        checkpoint_period, val_period, output_dir
    )
    cfg = add_fen_params(cfg, levels, patch_per_img, patch_size,
min_patch_size, erase_ratio, soften_ratio)
    cfg.MODEL.FEN.USE_FEN = use_fen

    # Start Training
    trainer = FENTrainer(cfg=cfg)
    trainer.resume_or_load(False)
    trainer.train()

    # Save configuration file to 'cfg.OUTPUT_DIR'.
    cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, 'model_final.pth')
    save_config(cfg, save_path=os.path.join(cfg.OUTPUT_DIR, 'config.yaml'))

This is the error message I got.

Config and Weights for "X101-FPN" is loaded.

---------------------------------------------------------------------------

AssertionError                            Traceback (most recent call last)

<ipython-input-19-43fa2d8d716d> <https://localhost:8080/#> in <module>
    90         cfg, num_epoch, num_class, base_lr, num_workers,
batch_size,     91         data_root, input_size, noise_type,
noise_params, log_period,
---> 92         checkpoint_period, val_period, output_dir     93     )
    94     cfg = add_fen_params(cfg, levels, patch_per_img,
patch_size, min_patch_size, erase_ratio, soften_ratio)


------------------------------
3 frames
------------------------------

/usr/local/lib/python3.7/dist-packages/detectron2/data/catalog.py
<https://localhost:8080/#> in register(self, name, func)     35
 """     36         assert callable(func), "You must register a
function with `DatasetCatalog.register`!"
---> 37         assert name not in self, "Dataset '{}' is already
registered!".format(name)     38         self[name] = func     39

AssertionError: Dataset 'train' is already registered!
